# Generated by Django 4.2.10 on 2024-05-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RISAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule_change',
            name='date_decided',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
