# Generated by Django 4.2.10 on 2024-05-08 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RISAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RISAPP.category'),
        ),
    ]
