# Generated by Django 4.2.10 on 2024-05-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RISAPP', '0002_alter_rule_change_date_decided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule_change',
            name='rule_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('declined', 'DECLINED'), ('implemented', 'IMPLEMENTED')], default='pending', max_length=15, null=True),
        ),
    ]
