# Generated by Django 4.2.10 on 2024-05-09 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RISAPP', '0003_alter_rule_change_rule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule_change',
            name='user',
            field=models.ForeignKey(blank=True, default='objects', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
