# Generated by Django 4.2.10 on 2024-05-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RISAPP', '0003_rule_change_category_rule_change_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule_change',
            name='date_created',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rule_change',
            name='date_decided',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rule_change',
            name='rule_description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rule_change',
            name='rule_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('declined', 'DECLINED')], default='pending', max_length=8, null=True),
        ),
    ]
