# Generated by Django 4.2.10 on 2024-05-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RISAPP', '0005_alter_rule_change_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule_change',
            name='date_created',
            field=models.DateField(default=None, null=True),
        ),
    ]
