# Generated by Django 4.2.10 on 2024-05-09 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RISAPP', '0007_alter_rule_change_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule_change',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
