# Generated by Django 4.2.10 on 2024-05-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RISAPP', '0008_alter_rule_change_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule_change',
            name='user',
        ),
    ]
