# Generated by Django 4.2.10 on 2024-05-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RISAPP', '0009_remove_rule_change_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule_change',
            name='date_decided',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
