# Generated by Django 4.2.10 on 2024-05-10 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RISAPP', '0012_alter_rule_change_rule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule_change',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rule_change',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RISAPP.category'),
        ),
        migrations.AlterField(
            model_name='rule_change',
            name='rule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='RISAPP.rule'),
        ),
    ]
